/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#adc6ff",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-bright": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "secondary-container": "#6cf8bb",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        secondary: "#006c49",
        "on-tertiary-container": "#fffbff",
        "on-surface-variant": "#424754",
        background: "#f9f9ff",
        primary: "#0058be",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d8e3fb",
        "on-primary-fixed-variant": "#004395",
        "on-background": "#111c2d",
        "outline-variant": "#c2c6d6",
        "surface-container": "#e7eeff",
        "surface-variant": "#d8e3fb",
        "on-primary-fixed": "#001a42",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#2a1700",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fefcff",
        "surface-dim": "#cfdaf2",
        "on-secondary-fixed-variant": "#005236",
        "surface-tint": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "surface-container-high": "#dee8ff",
        "primary-container": "#2170e4",
        surface: "#f9f9ff",
        "on-secondary-container": "#00714d",
        error: "#ba1a1a",
        "on-secondary-fixed": "#002113",
        "inverse-primary": "#adc6ff",
        "tertiary-container": "#a36700",
        "inverse-surface": "#263143",
        "on-error": "#ffffff",
        tertiary: "#825100",
        outline: "#727785",
        "on-surface": "#111c2d",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-fixed": "#ffddb8",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#ecf1ff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-xl": "2.25rem",
        gutter: "1rem",
        margin: "1.25rem",
      },
      fontFamily: {
        "bilingual-caption": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "bilingual-caption": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-lg": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "18px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
